version: "3.8"
services:
  database:
    image: postgis/postgis:13-3.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=agreeto
      - POSTGRES_USER=agreeto
      - POSTGRES_PASSWORD=22agreeto2022
    ports: ["5432:5432"]
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
