name: Checks
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run check
        run: npm run style:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run check
        run: npm run lint:check

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run check
        run: npm run types:check
