name: Checks
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run check
        run: npm run style:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run check
        run: npm run lint:check

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run check
        run: npm run types:check

  build:
    name: build - ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["chromium", "firefox"]
        include:
          - target: chromium
            file_path: ./packaged/chromium.zip
          - target: firefox
            file_path: ./packaged/firefox.xpi
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build signed Firefox extension
        if: ${{ matrix.target == 'firefox' }}
        run: npm run sign:firefox
        env:
          WEB_EXT_API_KEY: ${{ secrets.MOZILLA_WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.MOZILLA_WEB_EXT_API_SECRET }}

      - name: Build Chromium binary
        if: ${{ matrix.target == 'chromium' }}
        run: npm run package:chromium

      - name: Upload result to Slack
        if: ${{ success() }}
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: ${{ matrix.file_path }}
          channel: preview
          initial_comment: Build for commit `${{ github.sha }}` succeeded (${{ matrix.target }})

      - name: Upload error to Slack
        if: ${{ failure() }}
        uses: archive/github-actions-slack@v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: preview
          slack-text: Build for commit `${{ github.sha }}` failed (${{ matrix.target }})
